language: java

jdk: oraclejdk8

before_install:
    - pwd
    - mvn -v
    - echo ${M2_HOME}
    - cd dependencies
    - copy -R org ~/.m2/

script:
    - mvn clean test

after_success:
#    - bash <(curl -s https://codecov.io/bash)