language: java

jdk: oraclejdk8

before_install:
    - mvn -v
    - mvn install:install-file -Dfile=./dependencies/shardbatis-2.0.0B.jar -DgroupId=org.shardbatis -DartifactId=shardbatis -Dversion=2.0.0B -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true

script:
    - mvn clean test

after_success:
    - bash <(curl -s https://codecov.io/bash)